### ISSUE TITLE
Saving simulation configuration path issue

### ISSUE THREAD

**Issue by Clopeq** [rnickel1/HRAP_Source#1]
### issue description:

When saving simulaiton configuration all I get is a windows error beep sound and no notification on what happend, after a little bit of digging around I have found that the file didn't save at all. 

Then I tried to run the code from the matlab directly and i got the message:

![image](https://github.com/rnickel1/HRAP_Source/assets/26044095/924f9f9e-df57-4f51-83c1-c9c2dda52924)

Turns out the propellant configuration has to be loaded. After loading a propellant configuration I got another message:

![image](https://github.com/rnickel1/HRAP_Source/assets/26044095/8f14f4a3-6be4-407f-ac29-05063dcac0cb)

this time it turns out that the file path is hardcoded and since I have installed the application in another location it didn't work. After fixing the file path. the "Save simulation configuration" button did not produce any windows *beep sounds, nor does the matlab produce any error messages. Checking the file location I can confirm that the file indeed has been saved

### expected behavior:
The application is expected to notifiy the user whether the save was successfull or not. Also the filepathis hardcoded, it should adapt to the install location or be specify by the user much like during loading the simulation configuration.

**Comment by rnickel1** [comment]
Noted. A solution may be to do a drop down menu for save location as has been done for propellant and motor configs.
